Repository collab-community/Leetcode-problem, pull requests merged in 2022-08, with the labels that each got.

#5 add contributors welcome badge instead of section
  README.md
Labels: documentation, size/XS

#3 add required links
  Problem/Twosum.md
Labels: size/S

#7 docs: fix typo's, grammar, etc.
  README.md
Labels: documentation, size/XS

#8 wrote about leetcode and also provided the link for the website
  README.md
Labels: size/XS

#9 updated README.md file and added contribution guideline
  CONTRIBUTING.md
  LICENSE
  README.md
Labels: size/M
